# Generated by Django 3.1.2 on 2020-10-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_Name', models.CharField(max_length=20)),
                ('move_Rate', models.PositiveSmallIntegerField(default=0)),
                ('jump_Rate', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('physical_Evasion_Rate', models.PositiveSmallIntegerField(default=0)),
                ('base_Attack', models.CharField(choices=[('very low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('average', 'Average'), ('high', 'High')], default='low', max_length=10)),
                ('base_Magic', models.CharField(choices=[('very low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('average', 'Average'), ('high', 'High')], default='low', max_length=10)),
                ('base_HP', models.CharField(choices=[('very low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('average', 'Average'), ('high', 'High')], default='low', max_length=10)),
                ('base_MP', models.CharField(choices=[('very low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('average', 'Average'), ('high', 'High')], default='low', max_length=10)),
            ],
        ),
    ]
