# Generated by Django 3.1.2 on 2020-10-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftactics_api', '0002_auto_20201004_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='base_Attack',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('medium', 'Medium'), ('low', 'Low'), ('very low', 'Very Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='base_HP',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('medium', 'Medium'), ('low', 'Low'), ('very low', 'Very Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='base_MP',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('medium', 'Medium'), ('low', 'Low'), ('very low', 'Very Low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='base_Magic',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('medium', 'Medium'), ('low', 'Low'), ('very low', 'Very Low')], default='low', max_length=10),
        ),
    ]
