# Generated by Django 3.1.2 on 2020-11-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftactics_api', '0003_auto_20201004_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='base_Attack',
            new_name='base_attack',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='base_HP',
            new_name='base_hp',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='base_MP',
            new_name='base_mp',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='move_Rate',
            new_name='moverate',
        ),
    ]
