# Generated by Django 3.1.2 on 2020-11-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftactics_api', '0004_auto_20201115_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='base_Magic',
            new_name='base_magic',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='class_Name',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jump_Rate',
            new_name='jump_rate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='moverate',
            new_name='move_rate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='physical_Evasion_Rate',
            new_name='physical_evasion_rate',
        ),
    ]
