# Generated by Django 3.1.2 on 2020-11-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftactics_api', '0006_auto_20201115_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Class_name',
            new_name='class_name',
        ),
    ]
